### ISSUE TITLE
What is the license for this repo?

### ISSUE THREAD

**Issue by raarts** [digitalr00ts/docker-saltstack#1]
Thanks for this, looks really good. I'd like to re-use it for an internal project if you allow it.

**Comment by drts01** [comment]
Hi, thanks! Please use it. I have added the LGPL to it. FYI, I have not verified it under the 2018 version of Salt. I should be getting back to this soon.

**Comment by drts01** [comment]
well it does seem to still be passing my basic travis tests, https://travis-ci.org/digitalr00ts/docker-saltstack/builds/412970396 :)

**Comment by raarts** [comment]
Yes, it seems to work fine for me too.
